name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Get Current Time
      id: time
      run: echo "time=$(date +'%Y-%m-%d %H:%M:%S KST' -d '+9 hours')" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/simple-web-service:latest
        build-args: |
          APP_VERSION=${{ github.sha }}
          DEPLOY_TIME=${{ env.time }}